on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/utils
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: "20"
          registry-url: "https://registry.npmjs.org/"
          scope: "@polgubau"

      - run: npm install -g pnpm
      - run: pnpm install
      - run: pnpm build
      - run: pnpm coverage
      - name: Publish Results Badge
        uses: wjervis7/vitest-badge-action@v1.0.0
        if: success() || failure() # run whether steps succeed or not
        with:
          result-type: lines
          gist-token: ${{ secrets.GIST_TOKEN }} # if you want to upload badge to gist
          gist-url: https://gist.github.com/{org/user}/{gist_id}
          upload-badge: ${{ github.base_ref == 'refs/heads/main' }}
      
      - name: Publish Results
        uses: davelosert/vitest-coverage-report-action@v2
        if: (success() || failure())

      - name: Publish Results Badge
        uses: wjervis7/vitest-badge-action@v1.0.0
        if: (success() || failure())
        with:
          result-type: lines
          gist-token: ${{ secrets.GIST_TOKEN }}
          gist-url: ${{ vars.GIST_URL }}
          badge-path: badge-lines.svg
          badge-text: Coverage (Lines)
          upload-badge: ${{ steps.branch.outputs.branch == 'main' }}

      - name: Publish Results Badge
        uses: wjervis7/vitest-badge-action@v1.0.0
        if: (success() || failure())
        with:
          result-type: statements
          gist-token: ${{ secrets.GIST_TOKEN }}
          gist-url: ${{ vars.GIST_URL }}
          badge-path: badge-statements.svg
          badge-text: Coverage (Statements)
          upload-badge: ${{ steps.branch.outputs.branch == 'main' }}

      - name: Publish Results Badge
        uses: wjervis7/vitest-badge-action@v1.0.0
        if: (success() || failure())
        with:
          result-type: functions
          gist-token: ${{ secrets.GIST_TOKEN }}
          gist-url: ${{ vars.GIST_URL }}
          badge-path: badge-functions.svg
          badge-text: Coverage (Functions)
          upload-badge: ${{ steps.branch.outputs.branch == 'main' }}

      - name: Publish Results Badge
        uses: wjervis7/vitest-badge-action@v1.0.0
        if: success() || failure()
        with:
          result-type: branches
          gist-token: ${{ secrets.GIST_TOKEN }}
          gist-url: ${{ vars.GIST_URL }}
          badge-path: badge-branches.svg
          badge-text: Coverage (Branches)
          upload-badge: ${{ steps.branch.outputs.branch == 'main' }}


